import type { RenderFile } from "../model.js";

export const deploymentGeneratedHeader = "# Generated by deploy-config-schema deployment compiler. Edit deployment sources instead.";
export const deploymentSourceHeaderPrefix = "# Source: ";

export type RenderSourceKind = "model-rendered" | "pack-sourced" | "collection-sourced" | "carried";

export function renderManagedDeploymentContent(file: RenderFile): string {
  return `${deploymentGeneratedHeader}\n${deploymentSourceHeaderPrefix}${renderSourceKind(file)}\n${file.content.trimEnd()}\n`;
}

export function sortRenderFiles(files: RenderFile[]): RenderFile[] {
  return [...files].sort((left, right) => left.path.localeCompare(right.path) || left.adapter.localeCompare(right.adapter));
}

export function assertSafeRenderPath(path: string): void {
  if (path.startsWith("/") || path.includes("\0") || path.split(/[\\/]+/).includes("..")) {
    throw new Error(`unsafe render path: ${path}`);
  }
}

export function renderSourceKind(file: RenderFile): RenderSourceKind {
  if (file.adapter === "pack-sourced" || file.adapter === "flux-packs" || file.adapter === "flux-source") return "pack-sourced";
  if (file.adapter === "collection-sourced") return "collection-sourced";
  if (file.adapter === "carried-parity") return "carried";
  return "model-rendered";
}
