import type { RenderFile } from "../model.js";

export const deploymentGeneratedHeader = "# Generated by deploy-config-schema deployment compiler. Edit deployment sources instead.";

export function renderManagedDeploymentContent(file: RenderFile): string {
  return `${deploymentGeneratedHeader}\n${file.content.trimEnd()}\n`;
}

export function sortRenderFiles(files: RenderFile[]): RenderFile[] {
  return [...files].sort((left, right) => left.path.localeCompare(right.path) || left.adapter.localeCompare(right.adapter));
}

export function assertSafeRenderPath(path: string): void {
  if (path.startsWith("/") || path.includes("\0") || path.split(/[\\/]+/).includes("..")) {
    throw new Error(`unsafe render path: ${path}`);
  }
}
