// Generated by scripts/generate-schemas.ts. Do not edit by hand.

export const platformJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.extratoast.com/platform.schema.json",
  "title": "ExtraToast Minimal Platform Intent",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "name",
    "domain"
  ],
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "name": {
      "$ref": "#/$defs/identifier"
    },
    "domain": {
      "$ref": "#/$defs/hostname"
    },
    "cluster": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kind": {
          "enum": [
            "k3s",
            "kubernetes",
            "custom"
          ]
        },
        "api": {
          "type": "string",
          "pattern": "^https://"
        },
        "bootstrap": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "gitops": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "root": {
          "$ref": "#/$defs/relativePath"
        },
        "environment": {
          "$ref": "#/$defs/identifier"
        },
        "interval": {
          "$ref": "#/$defs/duration"
        },
        "intervals": {
          "$ref": "#/$defs/duration"
        }
      }
    },
    "sites": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/$defs/identifier"
      },
      "additionalProperties": {
        "$ref": "#/$defs/site"
      }
    },
    "hosts": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/$defs/identifier"
      },
      "additionalProperties": {
        "$ref": "#/$defs/host"
      }
    },
    "packs": {
      "type": "object",
      "additionalProperties": true
    },
    "services": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/$defs/identifier"
      },
      "additionalProperties": {
        "$ref": "#/$defs/service"
      }
    }
  },
  "$defs": {
    "identifier": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9._-]*$"
    },
    "hostname": {
      "type": "string",
      "pattern": "^(root|[a-z0-9][a-z0-9.-]*[a-z0-9])$"
    },
    "duration": {
      "type": "string",
      "pattern": "^[0-9]+(s|m|h|d)$"
    },
    "relativePath": {
      "type": "string",
      "minLength": 1,
      "not": {
        "pattern": "^/"
      }
    },
    "absolutePath": {
      "type": "string",
      "pattern": "^/"
    },
    "quantity": {
      "type": "string",
      "pattern": "^[0-9]+(m|Mi|Gi|Ti)?$"
    },
    "site": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kind": {
          "enum": [
            "home",
            "vps",
            "cloud",
            "edge",
            "lab",
            "colo",
            "custom"
          ]
        },
        "purpose": {
          "$ref": "#/$defs/identifier"
        },
        "region": {
          "$ref": "#/$defs/identifier"
        },
        "lanIngress": {
          "type": "string",
          "minLength": 1
        },
        "wan": {
          "type": "string",
          "minLength": 1
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "host": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "site": {
          "$ref": "#/$defs/identifier"
        },
        "system": {
          "enum": [
            "x86_64-linux",
            "aarch64-linux"
          ]
        },
        "roles": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "capabilities": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "ssh": {
          "type": "string",
          "minLength": 1
        },
        "hostModule": {
          "$ref": "#/$defs/relativePath"
        },
        "taints": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        "capacity": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "cpuMillicores": {
              "type": "integer",
              "minimum": 1
            },
            "memoryMiB": {
              "type": "integer",
              "minimum": 1
            }
          }
        }
      }
    },
    "service": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "image",
        "port"
      ],
      "properties": {
        "group": {
          "$ref": "#/$defs/identifier"
        },
        "namespace": {
          "$ref": "#/$defs/identifier"
        },
        "image": {
          "type": "string",
          "minLength": 1
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "route": {
          "oneOf": [
            {
              "enum": [
                "root"
              ]
            },
            {
              "type": "string",
              "pattern": "^/"
            },
            {
              "$ref": "#/$defs/route"
            }
          ]
        },
        "health": {
          "oneOf": [
            {
              "type": "string",
              "pattern": "^/"
            },
            {
              "$ref": "#/$defs/health"
            }
          ]
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "secrets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/secret"
          }
        },
        "storage": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/storage"
          }
        },
        "gpu": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "vendor": {
              "enum": [
                "amd",
                "nvidia",
                "intel"
              ]
            },
            "class": {
              "$ref": "#/$defs/identifier"
            },
            "count": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "schedule": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "site": {
              "$ref": "#/$defs/identifier"
            },
            "node": {
              "$ref": "#/$defs/identifier"
            },
            "requiredCapabilities": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/identifier"
              }
            },
            "spread": {
              "$ref": "#/$defs/identifier"
            },
            "arch": {
              "enum": [
                "amd64",
                "arm64"
              ]
            }
          }
        },
        "rollout": {
          "enum": [
            "latest",
            "pinned",
            "manual"
          ]
        },
        "managed": {
          "enum": [
            true,
            false,
            "partial"
          ]
        },
        "preserve": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/relativePath"
          }
        }
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "host": {
          "$ref": "#/$defs/hostname"
        },
        "path": {
          "$ref": "#/$defs/absolutePath"
        },
        "stripPrefix": {
          "$ref": "#/$defs/absolutePath"
        },
        "priority": {
          "type": "integer"
        },
        "exposure": {
          "enum": [
            "public",
            "public_and_lan",
            "lan_only",
            "internal_only"
          ]
        },
        "sso": {
          "type": "boolean"
        },
        "origin": {
          "$ref": "#/$defs/identifier"
        },
        "port": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "health": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "path": {
          "$ref": "#/$defs/absolutePath"
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "expectedStatus": {
          "type": "integer",
          "minimum": 100,
          "maximum": 599
        }
      }
    },
    "secret": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ref"
      ],
      "properties": {
        "ref": {
          "$ref": "#/$defs/identifier"
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        },
        "source": {
          "enum": [
            "kubernetes_secret",
            "vso_static",
            "vault_kv",
            "vault_dynamic_database",
            "vault_dynamic_rabbitmq",
            "vault_transit"
          ]
        }
      }
    },
    "storage": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "mount"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "mount": {
          "$ref": "#/$defs/absolutePath"
        },
        "size": {
          "$ref": "#/$defs/quantity"
        },
        "hostPath": {
          "$ref": "#/$defs/absolutePath"
        },
        "node": {
          "$ref": "#/$defs/identifier"
        }
      }
    }
  }
};

export const deployConfigJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.extratoast.com/deploy-config.schema.json",
  "title": "ExtraToast Deploy Config",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "cluster",
    "sites",
    "nodes",
    "service_intent",
    "placement_intent",
    "exposure_intent",
    "access_intent",
    "ingress_intent",
    "monitoring_intent",
    "image_metadata",
    "adapter_output_intent"
  ],
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "cluster": {
      "$ref": "#/$defs/cluster"
    },
    "sites": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$ref": "#/$defs/identifier"
      },
      "additionalProperties": {
        "$ref": "#/$defs/site"
      }
    },
    "nodes": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$ref": "#/$defs/identifier"
      },
      "additionalProperties": {
        "$ref": "#/$defs/node"
      }
    },
    "service_intent": {
      "$ref": "#/$defs/serviceIntent"
    },
    "placement_intent": {
      "$ref": "#/$defs/placementIntent"
    },
    "exposure_intent": {
      "$ref": "#/$defs/exposureIntent"
    },
    "access_intent": {
      "$ref": "#/$defs/accessIntent"
    },
    "ingress_intent": {
      "$ref": "#/$defs/ingressIntent"
    },
    "monitoring_intent": {
      "$ref": "#/$defs/monitoringIntent"
    },
    "image_metadata": {
      "$ref": "#/$defs/imageMetadata"
    },
    "adapter_output_intent": {
      "$ref": "#/$defs/adapterOutputIntent"
    },
    "extensions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "nomad": {
          "type": "object",
          "description": "Reserved extension area for future Nomad inputs. No renderer consumes it in this feature.",
          "additionalProperties": true
        }
      }
    }
  },
  "$defs": {
    "identifier": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9._-]*$"
    },
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "absolutePath": {
      "type": "string",
      "pattern": "^/"
    },
    "hostname": {
      "type": "string",
      "pattern": "^(root|[a-z0-9][a-z0-9.-]*[a-z0-9])$"
    },
    "serviceName": {
      "$ref": "#/$defs/identifier"
    },
    "serviceList": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/serviceName"
      }
    },
    "pathList": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^/"
      }
    },
    "cluster": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "public_domain",
        "kubernetes"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "public_domain": {
          "$ref": "#/$defs/hostname"
        },
        "kubernetes": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "bootstrap_control_plane",
            "api_server_endpoint",
            "control_plane_token_file",
            "worker_join_token_file"
          ],
          "properties": {
            "bootstrap_control_plane": {
              "$ref": "#/$defs/identifier"
            },
            "api_server_endpoint": {
              "type": "string",
              "pattern": "^https://"
            },
            "control_plane_token_file": {
              "$ref": "#/$defs/absolutePath"
            },
            "worker_join_token_file": {
              "$ref": "#/$defs/absolutePath"
            }
          }
        }
      }
    },
    "site": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "purpose"
      ],
      "properties": {
        "kind": {
          "enum": [
            "home",
            "vps",
            "cloud",
            "edge",
            "lab"
          ]
        },
        "purpose": {
          "$ref": "#/$defs/identifier"
        },
        "networking": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "lan_ingress_ip": {
              "$ref": "#/$defs/nonEmptyString"
            },
            "wan_public_ip": {
              "$ref": "#/$defs/nonEmptyString"
            }
          }
        }
      }
    },
    "node": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "site",
        "arch",
        "target_roles",
        "capacity",
        "capabilities"
      ],
      "properties": {
        "status": {
          "enum": [
            "active",
            "install-ready",
            "planned",
            "retired"
          ]
        },
        "site": {
          "$ref": "#/$defs/identifier"
        },
        "arch": {
          "enum": [
            "amd64",
            "arm64"
          ]
        },
        "ssh": {
          "$ref": "#/$defs/ssh"
        },
        "bootstrap_ssh": {
          "$ref": "#/$defs/ssh"
        },
        "target_roles": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "capacity": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "cpu_millicores",
            "memory_mib"
          ],
          "properties": {
            "cpu_millicores": {
              "type": "integer",
              "minimum": 1
            },
            "memory_mib": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "gpus": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "vendor",
              "model",
              "class"
            ],
            "properties": {
              "vendor": {
                "enum": [
                  "amd",
                  "nvidia",
                  "intel"
                ]
              },
              "model": {
                "$ref": "#/$defs/identifier"
              },
              "class": {
                "$ref": "#/$defs/identifier"
              }
            }
          }
        },
        "capabilities": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        }
      }
    },
    "ssh": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "host",
        "user",
        "port"
      ],
      "properties": {
        "host": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "user": {
          "$ref": "#/$defs/identifier"
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        }
      }
    },
    "serviceIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kubernetes",
        "host_native"
      ],
      "properties": {
        "kubernetes": {
          "type": "object",
          "minProperties": 1,
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/serviceList"
          }
        },
        "host_native": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/serviceList"
          }
        }
      }
    },
    "placementIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "site_affinity",
        "node_affinity",
        "gpu_preferences"
      ],
      "properties": {
        "site_affinity": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        },
        "node_affinity": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        },
        "gpu_preferences": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "preferred_gpu_model"
            ],
            "properties": {
              "preferred_gpu_model": {
                "$ref": "#/$defs/identifier"
              },
              "temporary_gpu_model": {
                "$ref": "#/$defs/identifier"
              }
            }
          }
        }
      }
    },
    "exposureIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "public",
        "public_and_lan",
        "internal_only",
        "lan_only"
      ],
      "properties": {
        "public": {
          "$ref": "#/$defs/serviceList"
        },
        "public_and_lan": {
          "$ref": "#/$defs/serviceList"
        },
        "internal_only": {
          "$ref": "#/$defs/serviceList"
        },
        "lan_only": {
          "$ref": "#/$defs/serviceList"
        }
      }
    },
    "accessIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sso_protected",
        "host_labels",
        "root_redirect"
      ],
      "properties": {
        "sso_protected": {
          "$ref": "#/$defs/serviceList"
        },
        "host_labels": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/hostname"
          }
        },
        "root_redirect": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        }
      }
    },
    "ingressIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "defaults",
        "kubernetes_backends",
        "route_rules",
        "wan_origin_overrides"
      ],
      "properties": {
        "defaults": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "namespace",
            "public_ingress_class",
            "lan_ingress_class",
            "entrypoint",
            "tls"
          ],
          "properties": {
            "namespace": {
              "$ref": "#/$defs/identifier"
            },
            "public_ingress_class": {
              "$ref": "#/$defs/identifier"
            },
            "lan_ingress_class": {
              "$ref": "#/$defs/identifier"
            },
            "entrypoint": {
              "$ref": "#/$defs/identifier"
            },
            "tls": {
              "type": "boolean"
            },
            "public_dns_target": {
              "$ref": "#/$defs/hostname"
            },
            "sso_middleware": {
              "$ref": "#/$defs/identifier"
            }
          }
        },
        "kubernetes_backends": {
          "$ref": "#/$defs/backendMap"
        },
        "route_rules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/routeRule"
          }
        },
        "wan_origin_overrides": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "enum": [
              "home_direct",
              "edge_direct"
            ]
          }
        }
      }
    },
    "monitoringIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kubernetes_backends"
      ],
      "properties": {
        "kubernetes_backends": {
          "$ref": "#/$defs/backendMap"
        }
      }
    },
    "backendMap": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/$defs/serviceName"
      },
      "additionalProperties": {
        "$ref": "#/$defs/kubernetesBackend"
      }
    },
    "kubernetesBackend": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "namespace",
        "service",
        "port"
      ],
      "properties": {
        "namespace": {
          "$ref": "#/$defs/identifier"
        },
        "service": {
          "$ref": "#/$defs/identifier"
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "health": {
          "$ref": "#/$defs/healthProbe"
        },
        "extra_probes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/extraProbe"
          }
        }
      }
    },
    "healthProbe": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "http",
            "tcp"
          ],
          "default": "http"
        },
        "path": {
          "type": "string",
          "pattern": "^/",
          "default": "/"
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "expected_status": {
          "type": "integer",
          "minimum": 100,
          "maximum": 599
        },
        "probe_strategy": {
          "enum": [
            "internal",
            "external",
            "both"
          ]
        },
        "response_time_ms": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "extraProbe": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "port"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "type": {
          "enum": [
            "http",
            "tcp"
          ],
          "default": "tcp"
        },
        "path": {
          "type": "string",
          "pattern": "^/",
          "default": "/"
        },
        "expected_status": {
          "type": "integer",
          "minimum": 100,
          "maximum": 599
        },
        "group": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "routeRule": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "service"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "service": {
          "$ref": "#/$defs/serviceName"
        },
        "host_label": {
          "$ref": "#/$defs/hostname"
        },
        "access": {
          "enum": [
            "direct",
            "sso_protected",
            "cluster_internal",
            "token_protected"
          ]
        },
        "path_prefixes": {
          "$ref": "#/$defs/pathList"
        },
        "exact_paths": {
          "$ref": "#/$defs/pathList"
        },
        "excluded_path_prefixes": {
          "$ref": "#/$defs/pathList"
        },
        "excluded_exact_paths": {
          "$ref": "#/$defs/pathList"
        }
      }
    },
    "imageMetadata": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "workloads"
      ],
      "properties": {
        "workloads": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/serviceName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/imageWorkload"
          }
        }
      }
    },
    "imageWorkload": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "repository",
        "tag",
        "pull_policy",
        "source",
        "update"
      ],
      "properties": {
        "repository": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[^\\s:]+(/[^\\s:]+)*$"
        },
        "tag": {
          "type": "string",
          "minLength": 1
        },
        "pull_policy": {
          "enum": [
            "Always",
            "IfNotPresent",
            "Never"
          ]
        },
        "source": {
          "enum": [
            "first_party",
            "third_party"
          ]
        },
        "update": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "eligible",
            "strategy"
          ],
          "properties": {
            "eligible": {
              "type": "boolean"
            },
            "strategy": {
              "enum": [
                "latest_tag",
                "pinned"
              ]
            },
            "keel": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "policy",
                "match_tag",
                "trigger",
                "poll_schedule"
              ],
              "properties": {
                "policy": {
                  "$ref": "#/$defs/identifier"
                },
                "match_tag": {
                  "type": "boolean"
                },
                "trigger": {
                  "enum": [
                    "poll",
                    "webhook",
                    "approval"
                  ]
                },
                "poll_schedule": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        }
      }
    },
    "adapterOutputIntent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "adapters",
        "output_paths"
      ],
      "properties": {
        "adapters": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/adapterName"
          }
        },
        "output_paths": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/adapterName"
          },
          "additionalProperties": {
            "type": "string",
            "minLength": 1
          }
        },
        "namespaces": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/adapterName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        },
        "configmap_names": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/adapterName"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        }
      }
    },
    "adapterName": {
      "enum": [
        "traefik-public",
        "traefik-lan",
        "gatus",
        "edge-catalog",
        "edge-route-catalog",
        "image-metadata",
        "kubernetes",
        "flux-root",
        "flux-packs",
        "flux-source",
        "nix-hosts",
        "vso"
      ]
    }
  }
};

export const serviceIntentJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.extratoast.com/round3/service-intent.schema.json",
  "title": "ExtraToast Round 3 Service Intent Skeleton",
  "description": "Design-first schema for per-service special-casing and future Nomad input contracts. No production renderer consumes this schema in round 3.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "services"
  ],
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "services": {
      "type": "object",
      "minProperties": 1,
      "propertyNames": {
        "$ref": "#/$defs/identifier"
      },
      "additionalProperties": {
        "$ref": "#/$defs/serviceProfile"
      }
    },
    "renderer": {
      "$ref": "#/$defs/renderer"
    },
    "notes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/nonEmptyString"
      }
    }
  },
  "$defs": {
    "identifier": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9._-]*$"
    },
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "path": {
      "type": "string",
      "pattern": "^/"
    },
    "hostname": {
      "type": "string",
      "pattern": "^(root|[a-z0-9][a-z0-9.-]*[a-z0-9])$"
    },
    "duration": {
      "type": "string",
      "pattern": "^[0-9]+(s|m|h|d)$"
    },
    "quantity": {
      "type": "string",
      "pattern": "^[0-9]+(m|Mi|Gi|Ti)?$"
    },
    "serviceProfile": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "workload",
        "image"
      ],
      "properties": {
        "description": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "workload": {
          "$ref": "#/$defs/workload"
        },
        "image": {
          "$ref": "#/$defs/image"
        },
        "ports": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/port"
          }
        },
        "runtime": {
          "$ref": "#/$defs/runtime"
        },
        "secrets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/secretBinding"
          }
        },
        "storage": {
          "$ref": "#/$defs/storage"
        },
        "networking": {
          "$ref": "#/$defs/networking"
        },
        "gatus": {
          "$ref": "#/$defs/gatus"
        },
        "observability": {
          "$ref": "#/$defs/observability"
        },
        "scheduling": {
          "$ref": "#/$defs/scheduling"
        },
        "rollout": {
          "$ref": "#/$defs/rollout"
        },
        "kubernetes": {
          "$ref": "#/$defs/kubernetesContract"
        },
        "nomad": {
          "$ref": "#/$defs/nomadContract"
        },
        "unsupported_until": {
          "type": "array",
          "items": {
            "enum": [
              "schema_review",
              "renderer_fixture",
              "platform_pack",
              "consumer_migration"
            ]
          }
        }
      }
    },
    "workload": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "enum": [
            "deployment",
            "statefulset",
            "job",
            "cronjob",
            "external_service",
            "host_native",
            "nomad_job"
          ]
        },
        "replicas": {
          "type": "integer",
          "minimum": 0
        },
        "schedule": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "restart_policy": {
          "enum": [
            "Always",
            "OnFailure",
            "Never"
          ]
        },
        "strategy": {
          "enum": [
            "rolling",
            "recreate",
            "replace",
            "blue_green",
            "manual"
          ]
        }
      }
    },
    "image": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "repository",
        "tag"
      ],
      "properties": {
        "repository": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "tag": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "pull_policy": {
          "enum": [
            "Always",
            "IfNotPresent",
            "Never"
          ]
        },
        "pull_secrets": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "source": {
          "enum": [
            "first_party",
            "third_party",
            "generated",
            "external"
          ]
        }
      }
    },
    "port": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "container_port"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "container_port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "protocol": {
          "enum": [
            "TCP",
            "UDP"
          ]
        },
        "service_port": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "exposure": {
          "enum": [
            "public",
            "lan",
            "internal",
            "metrics",
            "admin",
            "none"
          ]
        }
      }
    },
    "runtime": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "env": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "files": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "env_from": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/secretRef"
          }
        },
        "args": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "sidecars": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/containerLike"
          }
        },
        "init_containers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/containerLike"
          }
        }
      }
    },
    "containerLike": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "image"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "image": {
          "$ref": "#/$defs/image"
        },
        "args": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "secretRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "optional": {
          "type": "boolean"
        }
      }
    },
    "secretBinding": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "source"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "source": {
          "enum": [
            "kubernetes_secret",
            "vso_static",
            "vault_kv",
            "vault_dynamic_database",
            "vault_dynamic_rabbitmq",
            "vault_transit"
          ]
        },
        "ref": {
          "$ref": "#/$defs/identifier"
        },
        "mount_path": {
          "$ref": "#/$defs/path"
        },
        "env_keys": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "lease": {
          "$ref": "#/$defs/lease"
        }
      }
    },
    "lease": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "default_ttl": {
          "$ref": "#/$defs/duration"
        },
        "max_ttl": {
          "$ref": "#/$defs/duration"
        },
        "rotation_mode": {
          "enum": [
            "process_restart",
            "sidecar_renewal",
            "library_lifecycle",
            "manual"
          ]
        }
      }
    },
    "storage": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "volumes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/volume"
          }
        },
        "mounts": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/mount"
          }
        }
      }
    },
    "volume": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "kind"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "kind": {
          "enum": [
            "pvc",
            "host_path",
            "config_map",
            "secret",
            "empty_dir",
            "ephemeral"
          ]
        },
        "size": {
          "$ref": "#/$defs/quantity"
        },
        "storage_class": {
          "$ref": "#/$defs/identifier"
        },
        "path": {
          "$ref": "#/$defs/path"
        },
        "access_modes": {
          "type": "array",
          "items": {
            "enum": [
              "ReadWriteOnce",
              "ReadWriteMany",
              "ReadOnlyMany"
            ]
          }
        },
        "claim_template": {
          "type": "boolean"
        },
        "portable": {
          "type": "boolean"
        }
      }
    },
    "mount": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "volume",
        "path"
      ],
      "properties": {
        "volume": {
          "$ref": "#/$defs/identifier"
        },
        "path": {
          "$ref": "#/$defs/path"
        },
        "read_only": {
          "type": "boolean"
        }
      }
    },
    "networking": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "host_network": {
          "type": "boolean"
        },
        "routes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/route"
          }
        },
        "service_annotations": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "route": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "port"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "host": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "port": {
          "$ref": "#/$defs/identifier"
        },
        "paths": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/path"
          }
        },
        "bypass_paths": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/path"
          }
        },
        "access": {
          "enum": [
            "direct",
            "sso",
            "token",
            "internal"
          ]
        },
        "origin": {
          "$ref": "#/$defs/identifier"
        },
        "websocket": {
          "type": "boolean"
        },
        "root_redirect": {
          "$ref": "#/$defs/path"
        },
        "middleware_profile": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "gatus": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "endpoints": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/probe"
          }
        }
      }
    },
    "probe": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "type"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "type": {
          "enum": [
            "http",
            "tcp"
          ]
        },
        "port": {
          "$ref": "#/$defs/identifier"
        },
        "path": {
          "$ref": "#/$defs/path"
        },
        "expected_status": {
          "type": "integer",
          "minimum": 100,
          "maximum": 599
        },
        "strategy": {
          "enum": [
            "internal",
            "external",
            "both"
          ]
        },
        "group": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "observability": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "metrics": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/monitor"
          }
        },
        "logs": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "tracing": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "protocol": {
              "enum": [
                "otlp_http",
                "otlp_grpc",
                "none"
              ]
            }
          }
        }
      }
    },
    "monitor": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "port"
      ],
      "properties": {
        "kind": {
          "enum": [
            "ServiceMonitor",
            "PodMonitor"
          ]
        },
        "port": {
          "$ref": "#/$defs/identifier"
        },
        "path": {
          "$ref": "#/$defs/path"
        },
        "interval": {
          "$ref": "#/$defs/duration"
        }
      }
    },
    "scheduling": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "site_affinity": {
          "$ref": "#/$defs/identifier"
        },
        "node_affinity": {
          "$ref": "#/$defs/identifier"
        },
        "required_capabilities": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "gpu": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "class": {
              "$ref": "#/$defs/identifier"
            },
            "count": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "topology_spread": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        }
      }
    },
    "rollout": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "update_strategy": {
          "enum": [
            "pinned",
            "latest_tag",
            "semver",
            "manual"
          ]
        },
        "restart_triggers": {
          "type": "array",
          "items": {
            "enum": [
              "config",
              "secret",
              "image",
              "schedule",
              "manual"
            ]
          }
        },
        "availability": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "pdb_min_available": {
              "type": "integer",
              "minimum": 0
            },
            "max_unavailable": {
              "type": "integer",
              "minimum": 0
            }
          }
        },
        "autoscaling": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "enabled",
            "max_replicas"
          ],
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "min_replicas": {
              "type": "integer",
              "minimum": 1
            },
            "max_replicas": {
              "type": "integer",
              "minimum": 1
            },
            "target_cpu_utilization": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100
            },
            "target_memory_utilization": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100
            }
          }
        }
      }
    },
    "kubernetesContract": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "namespace_ref": {
          "$ref": "#/$defs/identifier"
        },
        "service_account_ref": {
          "$ref": "#/$defs/identifier"
        },
        "service_ref": {
          "$ref": "#/$defs/identifier"
        },
        "render_status": {
          "enum": [
            "design_only",
            "candidate",
            "implemented_elsewhere"
          ]
        },
        "resource_hints": {
          "type": "array",
          "items": {
            "enum": [
              "Deployment",
              "StatefulSet",
              "Job",
              "CronJob",
              "Service",
              "IngressRoute",
              "PVC",
              "PDB",
              "HPA",
              "ServiceMonitor",
              "PodMonitor",
              "VaultStaticSecret"
            ]
          }
        },
        "pod_spec": {
          "type": "object",
          "additionalProperties": true
        },
        "raw_manifests": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "nomadContract": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "renderer_status",
        "implementation_prerequisites"
      ],
      "properties": {
        "renderer_status": {
          "const": "design_only"
        },
        "implementation_prerequisites": {
          "type": "array",
          "minItems": 1,
          "items": {
            "enum": [
              "representative_input_fixture",
              "expected_output_fixture",
              "operator_review",
              "platform_boundary_review"
            ]
          }
        },
        "datacenters": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "groups": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nomadGroup"
          }
        },
        "restart": {
          "type": "object",
          "additionalProperties": true
        },
        "update": {
          "type": "object",
          "additionalProperties": true
        }
      }
    },
    "nomadGroup": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "count": {
          "type": "integer",
          "minimum": 1
        },
        "tasks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nomadTask"
          }
        },
        "volumes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/volume"
          }
        },
        "networks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/port"
          }
        }
      }
    },
    "nomadTask": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "driver"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "driver": {
          "enum": [
            "docker",
            "exec",
            "java",
            "raw_exec",
            "custom"
          ]
        },
        "resources": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "cpu_mhz": {
              "type": "integer",
              "minimum": 1
            },
            "memory_mb": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "services": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nomadService"
          }
        },
        "templates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nomadTemplate"
          }
        }
      }
    },
    "nomadService": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "port"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "port": {
          "$ref": "#/$defs/identifier"
        },
        "checks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/probe"
          }
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "nomadTemplate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "destination"
      ],
      "properties": {
        "destination": {
          "$ref": "#/$defs/path"
        },
        "source_ref": {
          "$ref": "#/$defs/identifier"
        },
        "change_mode": {
          "enum": [
            "noop",
            "signal",
            "restart",
            "script"
          ]
        }
      }
    },
    "renderer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "cluster_name": {
          "$ref": "#/$defs/identifier"
        },
        "public_domain": {
          "$ref": "#/$defs/hostname"
        },
        "host_native_node": {
          "$ref": "#/$defs/identifier"
        },
        "adapters": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "enum": [
              "traefik-public",
              "traefik-lan",
              "gatus",
              "edge-catalog",
              "edge-route-catalog",
              "image-metadata",
              "kubernetes",
              "flux-root",
              "flux-packs",
              "flux-source",
              "nix-hosts",
              "vso"
            ]
          }
        },
        "output_paths": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "namespaces": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        },
        "configmap_names": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/identifier"
          }
        },
        "ingress_defaults": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "namespace": {
              "$ref": "#/$defs/identifier"
            },
            "public_ingress_class": {
              "$ref": "#/$defs/identifier"
            },
            "lan_ingress_class": {
              "$ref": "#/$defs/identifier"
            },
            "entrypoint": {
              "$ref": "#/$defs/identifier"
            },
            "tls": {
              "type": "boolean"
            },
            "public_dns_target": {
              "$ref": "#/$defs/hostname"
            },
            "sso_middleware": {
              "$ref": "#/$defs/identifier"
            }
          }
        }
      }
    }
  }
};

export const fleetInventoryJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.extratoast.com/round3/fleet-inventory.schema.json",
  "title": "ExtraToast Round 3 Fleet Inventory Extension Skeleton",
  "description": "Design-first schema for richer sites, nodes, capabilities, placement, origins, exposure, SSO, and renderer target selection.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "fleet"
  ],
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "fleet": {
      "$ref": "#/$defs/fleet"
    }
  },
  "$defs": {
    "identifier": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9._-]*$"
    },
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "hostname": {
      "type": "string",
      "pattern": "^(root|[a-z0-9][a-z0-9.-]*[a-z0-9])$"
    },
    "duration": {
      "type": "string",
      "pattern": "^[0-9]+(s|m|h|d)$"
    },
    "fleet": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "cluster",
        "sites",
        "nodes",
        "capabilities",
        "placement",
        "origins",
        "exposure",
        "sso",
        "renderer_targets"
      ],
      "properties": {
        "cluster": {
          "$ref": "#/$defs/cluster"
        },
        "sites": {
          "type": "object",
          "minProperties": 1,
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/site"
          }
        },
        "nodes": {
          "type": "object",
          "minProperties": 1,
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/node"
          }
        },
        "capabilities": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/capability"
          }
        },
        "placement": {
          "$ref": "#/$defs/placement"
        },
        "origins": {
          "type": "object",
          "minProperties": 1,
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/origin"
          }
        },
        "exposure": {
          "$ref": "#/$defs/exposure"
        },
        "sso": {
          "$ref": "#/$defs/sso"
        },
        "renderer_targets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/rendererTarget"
          }
        }
      }
    },
    "cluster": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "domain"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "domain": {
          "$ref": "#/$defs/hostname"
        },
        "platform": {
          "enum": [
            "kubernetes",
            "nomad",
            "mixed",
            "inventory_only"
          ]
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "site": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "purpose"
      ],
      "properties": {
        "kind": {
          "enum": [
            "home",
            "vps",
            "cloud",
            "edge",
            "lab",
            "colo",
            "custom"
          ]
        },
        "purpose": {
          "$ref": "#/$defs/identifier"
        },
        "region": {
          "$ref": "#/$defs/identifier"
        },
        "networking": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "lan_cidrs": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/nonEmptyString"
              }
            },
            "wan_address_ref": {
              "$ref": "#/$defs/identifier"
            },
            "lan_ingress_address_ref": {
              "$ref": "#/$defs/identifier"
            },
            "tailnet": {
              "type": "boolean"
            }
          }
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "node": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "site",
        "arch",
        "roles",
        "capacity",
        "capabilities"
      ],
      "properties": {
        "status": {
          "enum": [
            "active",
            "install_ready",
            "planned",
            "retired",
            "maintenance"
          ]
        },
        "site": {
          "$ref": "#/$defs/identifier"
        },
        "arch": {
          "enum": [
            "amd64",
            "arm64",
            "armv7",
            "riscv64"
          ]
        },
        "roles": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "capacity": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "cpu_millicores",
            "memory_mib"
          ],
          "properties": {
            "cpu_millicores": {
              "type": "integer",
              "minimum": 1
            },
            "memory_mib": {
              "type": "integer",
              "minimum": 1
            },
            "ephemeral_storage_mib": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "capabilities": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "accelerators": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/accelerator"
          }
        },
        "addresses": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "accelerator": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "vendor",
        "model",
        "class"
      ],
      "properties": {
        "vendor": {
          "$ref": "#/$defs/identifier"
        },
        "model": {
          "$ref": "#/$defs/identifier"
        },
        "class": {
          "$ref": "#/$defs/identifier"
        },
        "count": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "capability": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "description"
      ],
      "properties": {
        "description": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "scope": {
          "enum": [
            "node",
            "site",
            "cluster",
            "renderer"
          ]
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "placement": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/placementRule"
          }
        }
      }
    },
    "placementRule": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "selector"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "selector": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "sites": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/identifier"
              }
            },
            "nodes": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/identifier"
              }
            },
            "required_capabilities": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/identifier"
              }
            },
            "accelerator_classes": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/identifier"
              }
            }
          }
        },
        "applies_to": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "fallback": {
          "enum": [
            "fail",
            "soft_preference",
            "manual_override"
          ]
        }
      }
    },
    "origin": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "enum": [
            "proxied_dns",
            "direct_wan",
            "direct_lan",
            "internal_service",
            "custom"
          ]
        },
        "address_ref": {
          "$ref": "#/$defs/identifier"
        },
        "site": {
          "$ref": "#/$defs/identifier"
        },
        "provider": {
          "$ref": "#/$defs/identifier"
        },
        "proxied": {
          "type": "boolean"
        },
        "ttl": {
          "$ref": "#/$defs/duration"
        },
        "metadata": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "exposure": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "classes": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/exposureClass"
          }
        },
        "services": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/serviceExposure"
          }
        }
      }
    },
    "exposureClass": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "reachability"
      ],
      "properties": {
        "reachability": {
          "enum": [
            "public",
            "public_and_lan",
            "lan_only",
            "internal_only",
            "monitoring_only",
            "custom"
          ]
        },
        "default_origin": {
          "$ref": "#/$defs/identifier"
        },
        "renderer_hints": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        }
      }
    },
    "serviceExposure": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "class"
      ],
      "properties": {
        "class": {
          "$ref": "#/$defs/identifier"
        },
        "host_label": {
          "$ref": "#/$defs/hostname"
        },
        "origin": {
          "$ref": "#/$defs/identifier"
        },
        "sso_policy": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "sso": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "policies": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/ssoPolicy"
          }
        }
      }
    },
    "ssoPolicy": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "mode"
      ],
      "properties": {
        "mode": {
          "enum": [
            "none",
            "forward_auth",
            "oidc",
            "token",
            "custom"
          ]
        },
        "provider_ref": {
          "$ref": "#/$defs/identifier"
        },
        "bypass_paths": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^/"
          }
        },
        "required_claims": {
          "type": "object",
          "additionalProperties": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/nonEmptyString"
            }
          }
        }
      }
    },
    "rendererTarget": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "kind",
        "status"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "kind": {
          "enum": [
            "traefik_routes",
            "gatus_endpoints",
            "edge_catalog",
            "image_metadata",
            "vault_policy_inputs",
            "nomad_jobs",
            "kubernetes_workloads",
            "custom"
          ]
        },
        "status": {
          "enum": [
            "implemented",
            "design_only",
            "external"
          ]
        },
        "consumes": {
          "type": "array",
          "items": {
            "enum": [
              "fleet",
              "service_intent",
              "vault_inputs",
              "images",
              "origins",
              "sso",
              "packs"
            ]
          }
        },
        "output_ref": {
          "$ref": "#/$defs/identifier"
        }
      }
    }
  }
};

export const vaultDynamicSecretsJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.extratoast.com/round3/vault-dynamic-secrets.schema.json",
  "title": "ExtraToast Round 3 Vault Dynamic Secret Input Skeleton",
  "description": "Design-first input schema for Vault auth, KV, transit, database, RabbitMQ, VSO, and service-consumer coordination. This schema does not generate policies, scripts, or manifests.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "vault"
  ],
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 1
    },
    "vault": {
      "$ref": "#/$defs/vault"
    }
  },
  "$defs": {
    "identifier": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9._-]*$"
    },
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "vaultPath": {
      "type": "string",
      "pattern": "^[a-z0-9][a-z0-9._/-]*$"
    },
    "duration": {
      "type": "string",
      "pattern": "^[0-9]+(s|m|h|d)$"
    },
    "vault": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "auth",
        "kv",
        "transit",
        "database",
        "rabbitmq",
        "vso",
        "service_consumers",
        "validation_fixtures"
      ],
      "properties": {
        "auth": {
          "$ref": "#/$defs/auth"
        },
        "kv": {
          "$ref": "#/$defs/kv"
        },
        "transit": {
          "$ref": "#/$defs/transit"
        },
        "database": {
          "$ref": "#/$defs/database"
        },
        "rabbitmq": {
          "$ref": "#/$defs/rabbitmq"
        },
        "vso": {
          "$ref": "#/$defs/vso"
        },
        "service_consumers": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/serviceConsumer"
          }
        },
        "validation_fixtures": {
          "$ref": "#/$defs/validationFixtures"
        }
      }
    },
    "auth": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kubernetes"
      ],
      "properties": {
        "kubernetes": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "mount",
            "roles"
          ],
          "properties": {
            "mount": {
              "$ref": "#/$defs/identifier"
            },
            "roles": {
              "type": "object",
              "propertyNames": {
                "$ref": "#/$defs/identifier"
              },
              "additionalProperties": {
                "$ref": "#/$defs/kubernetesRole"
              }
            }
          }
        }
      }
    },
    "kubernetesRole": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "bound_service_accounts",
        "policies"
      ],
      "properties": {
        "bound_service_accounts": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/serviceAccount"
          }
        },
        "policies": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "audiences": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "ttl": {
          "$ref": "#/$defs/duration"
        }
      }
    },
    "serviceAccount": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "namespace"
      ],
      "properties": {
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "namespace": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "kv": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "mount",
        "paths"
      ],
      "properties": {
        "mount": {
          "$ref": "#/$defs/identifier"
        },
        "paths": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/kvPath"
          }
        }
      }
    },
    "kvPath": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "path",
        "fields"
      ],
      "properties": {
        "path": {
          "$ref": "#/$defs/vaultPath"
        },
        "fields": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "owner": {
          "$ref": "#/$defs/identifier"
        },
        "purpose": {
          "$ref": "#/$defs/nonEmptyString"
        }
      }
    },
    "transit": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "keys": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/transitKey"
          }
        }
      }
    },
    "transitKey": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "allowed_operations"
      ],
      "properties": {
        "type": {
          "enum": [
            "rsa-2048",
            "rsa-3072",
            "rsa-4096",
            "ecdsa-p256",
            "ed25519",
            "aes256-gcm96"
          ]
        },
        "allowed_operations": {
          "type": "array",
          "minItems": 1,
          "items": {
            "enum": [
              "sign",
              "verify",
              "encrypt",
              "decrypt",
              "read_public_key"
            ]
          }
        },
        "rotation_period": {
          "$ref": "#/$defs/duration"
        }
      }
    },
    "database": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "engines": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/databaseEngine"
          }
        }
      }
    },
    "databaseEngine": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "plugin",
        "connection",
        "roles"
      ],
      "properties": {
        "plugin": {
          "enum": [
            "postgresql",
            "mysql",
            "mariadb",
            "custom"
          ]
        },
        "connection": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "url_template",
            "admin_secret_ref"
          ],
          "properties": {
            "url_template": {
              "$ref": "#/$defs/nonEmptyString"
            },
            "admin_secret_ref": {
              "$ref": "#/$defs/identifier"
            },
            "verify_connection": {
              "type": "boolean"
            }
          }
        },
        "roles": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/databaseRole"
          }
        }
      }
    },
    "databaseRole": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "default_ttl",
        "max_ttl",
        "creation_statements",
        "revocation_statements"
      ],
      "properties": {
        "default_ttl": {
          "$ref": "#/$defs/duration"
        },
        "max_ttl": {
          "$ref": "#/$defs/duration"
        },
        "grant_parent_role_ref": {
          "$ref": "#/$defs/identifier"
        },
        "creation_statements": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          }
        },
        "revocation_statements": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/nonEmptyString"
          }
        }
      }
    },
    "rabbitmq": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "engines": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/rabbitmqEngine"
          }
        }
      }
    },
    "rabbitmqEngine": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "connection",
        "roles"
      ],
      "properties": {
        "connection": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "uri",
            "admin_secret_ref"
          ],
          "properties": {
            "uri": {
              "$ref": "#/$defs/nonEmptyString"
            },
            "admin_secret_ref": {
              "$ref": "#/$defs/identifier"
            },
            "verify_connection": {
              "type": "boolean"
            }
          }
        },
        "roles": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/rabbitmqRole"
          }
        }
      }
    },
    "rabbitmqRole": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "default_ttl",
        "max_ttl",
        "vhosts"
      ],
      "properties": {
        "default_ttl": {
          "$ref": "#/$defs/duration"
        },
        "max_ttl": {
          "$ref": "#/$defs/duration"
        },
        "vhosts": {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": {
            "$ref": "#/$defs/rabbitmqPermissions"
          }
        }
      }
    },
    "rabbitmqPermissions": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "configure",
        "write",
        "read"
      ],
      "properties": {
        "configure": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "write": {
          "$ref": "#/$defs/nonEmptyString"
        },
        "read": {
          "$ref": "#/$defs/nonEmptyString"
        }
      }
    },
    "vso": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "auth_role",
        "static_syncs"
      ],
      "properties": {
        "auth_role": {
          "$ref": "#/$defs/identifier"
        },
        "static_syncs": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/vsoStaticSync"
          }
        },
        "dynamic_syncs": {
          "type": "object",
          "propertyNames": {
            "$ref": "#/$defs/identifier"
          },
          "additionalProperties": {
            "$ref": "#/$defs/vsoDynamicSync"
          }
        }
      }
    },
    "vsoStaticSync": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kv_path_ref",
        "target"
      ],
      "properties": {
        "kv_path_ref": {
          "$ref": "#/$defs/identifier"
        },
        "target": {
          "$ref": "#/$defs/kubernetesSecretTarget"
        },
        "rollout_restart_targets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/kubernetesWorkloadRef"
          }
        }
      }
    },
    "vsoDynamicSync": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "engine",
        "role",
        "target"
      ],
      "properties": {
        "engine": {
          "enum": [
            "database",
            "rabbitmq"
          ]
        },
        "role": {
          "$ref": "#/$defs/identifier"
        },
        "target": {
          "$ref": "#/$defs/kubernetesSecretTarget"
        },
        "rollout_restart_targets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/kubernetesWorkloadRef"
          }
        }
      }
    },
    "kubernetesSecretTarget": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "namespace",
        "name"
      ],
      "properties": {
        "namespace": {
          "$ref": "#/$defs/identifier"
        },
        "name": {
          "$ref": "#/$defs/identifier"
        },
        "type": {
          "enum": [
            "Opaque",
            "kubernetes.io/dockerconfigjson",
            "kubernetes.io/tls",
            "custom"
          ]
        }
      }
    },
    "kubernetesWorkloadRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "namespace",
        "name"
      ],
      "properties": {
        "kind": {
          "enum": [
            "Deployment",
            "StatefulSet",
            "DaemonSet",
            "Job",
            "CronJob"
          ]
        },
        "namespace": {
          "$ref": "#/$defs/identifier"
        },
        "name": {
          "$ref": "#/$defs/identifier"
        }
      }
    },
    "serviceConsumer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kubernetes_role_ref": {
          "$ref": "#/$defs/identifier"
        },
        "kv_path_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "transit_key_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "database_role_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "rabbitmq_role_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        },
        "credential_delivery": {
          "enum": [
            "spring_cloud_vault",
            "vault_agent",
            "vso_secret",
            "manual",
            "custom"
          ]
        }
      }
    },
    "validationFixtures": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "required_checks": {
          "type": "array",
          "items": {
            "enum": [
              "auth_role_has_policy",
              "vso_kv_path_declared",
              "database_role_has_ttl",
              "rabbitmq_vhost_declared",
              "transit_key_declared",
              "no_secret_values"
            ]
          }
        },
        "negative_cases": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/identifier"
          }
        }
      }
    }
  }
};
