// @ts-nocheck -- Deploy v2 command scaffolding moves heterogeneous source and
// lock documents through stable CLI contracts before the full compiler lands.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import YAML from "yaml";
import { loadConfig } from "../config-loader.js";
import { validateArtifact } from "../artifact-validator.js";

const generatedHeader = "# Generated by deploy-config-schema deploy-v2 compiler. Edit deployment sources instead.";

export function runBundle(args, streams, parseOptions) {
  const [subcommand, ...rest] = args;
  if (subcommand !== "pack") {
    writeDiagnostics(streams.stderr, usageDiagnostic("bundle pack --deploy-dir <dir> --images <file> --repo <repo> --git-sha <sha> --version <version> --out <file>"));
    return 1;
  }
  const { options, diagnostics } = parseOptions(rest);
  const required = ["deployDir", "images", "repo", "gitSha", "version", "out"];
  const missing = required.filter((key) => !options[key]);
  if (diagnostics.length > 0 || missing.length > 0) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : missing.map((key) => ({
      code: "E_USAGE",
      message: `--${optionName(key)} is required`,
      path: "/",
    })));
    return 1;
  }

  const deployFiles = listFiles(options.deployDir).filter((path) => /\.(json|ya?ml|env)$/.test(path));
  const images = readDocument(options.images);
  const manifest = {
    artifactType: "application/vnd.jorisjonkers.deployment.bundle.v1+tar",
    repo: options.repo,
    gitSha: options.gitSha,
    version: options.version,
    deployDir: options.deployDir,
    files: deployFiles.map((path) => ({
      path: relative(options.deployDir, path).replaceAll("\\", "/"),
      digest: sha256(readFileSync(path)),
    })),
    images,
  };

  mkdirSync(dirname(options.out), { recursive: true });
  writeFileSync(options.out, `${JSON.stringify(manifest, null, 2)}\n`);
  streams.stdout.write(`${JSON.stringify({
    out: options.out,
    manifestDigest: sha256(JSON.stringify(manifest)),
    files: manifest.files.length,
  }, null, 2)}\n`);
  return 0;
}

export function runResolveSources(args, streams, parseOptions) {
  const { options, diagnostics } = parseOptions(args);
  if (diagnostics.length > 0 || !options.sources || !options.lock) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : usageDiagnostic("resolve-sources --sources deployment-sources.yml --lock deployment.lock.yml [--check]"));
    return 1;
  }
  const validation = validateNamedInputs([
    ["deployment-sources-v1", options.sources],
    ["deployment-lock-v1", options.lock],
  ]);
  if (!validation.valid) {
    writeValidationResult(streams.stdout, validation);
    return 1;
  }
  const sources = readDocument(options.sources);
  const lock = readDocument(options.lock);
  const report = resolveSourcesReport(sources, lock);
  const ok = report.unlocked.length === 0;
  streams.stdout.write(`${JSON.stringify({ valid: ok, ...report }, null, 2)}\n`);
  return ok ? 0 : 1;
}

export function runLock(args, streams, parseOptions) {
  if (args[0] === "images") {
    return runLockImages(args.slice(1), streams, parseOptions);
  }
  const { options, diagnostics } = parseOptions(args);
  if (diagnostics.length > 0 || !options.sources || !options.lock) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : usageDiagnostic("lock --sources deployment-sources.yml --lock deployment.lock.yml [--update]"));
    return 1;
  }
  const validation = validateNamedInputs([
    ["deployment-sources-v1", options.sources],
    ["deployment-lock-v1", options.lock],
  ]);
  if (!validation.valid) {
    writeValidationResult(streams.stdout, validation);
    return 1;
  }
  const sources = readDocument(options.sources);
  const lock = readDocument(options.lock);
  const report = resolveSourcesReport(sources, lock);
  if (options.update) {
    const nextLock = {
      ...lock,
      metadata: {
        ...lock.metadata,
        generatedAt: lock.metadata?.generatedAt ?? "1970-01-01T00:00:00.000Z",
      },
    };
    writeFileSync(options.lock, stringifyDocument(options.lock, nextLock));
  }
  streams.stdout.write(`${JSON.stringify({
    valid: report.unlocked.length === 0,
    updated: Boolean(options.update),
    ...report,
  }, null, 2)}\n`);
  return report.unlocked.length === 0 ? 0 : 1;
}

export function runCompile(args, streams, parseOptions) {
  const { options, diagnostics } = parseOptions(args);
  if (diagnostics.length > 0 || !options.env || !options.sources || !options.lock || !options.nodeContract || !options.reachability || !options.out) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : usageDiagnostic("compile --env <name> --sources <path> --lock <path> --node-contract <path> --reachability <path> --out <dir> [--check]"));
    return 1;
  }
  const validation = validateNamedInputs([
    ["deployment-sources-v1", options.sources],
    ["deployment-lock-v1", options.lock],
    ["node-contract-v1", options.nodeContract],
    ["reachability-v1", options.reachability],
  ]);
  if (!validation.valid) {
    writeValidationResult(streams.stdout, validation);
    return 1;
  }
  const report = compileReport(options);
  const files = compileFiles(report);
  const result = writeManagedFiles(files, options.out, { check: options.check });
  streams.stdout.write(`${JSON.stringify({ ok: result.ok, report, results: result.results, diagnostics: result.diagnostics }, null, 2)}\n`);
  return result.ok ? 0 : 1;
}

export function runRenderFlux(args, streams, parseOptions) {
  const { options, diagnostics } = parseOptions(args);
  const repo = options.repo ?? ".";
  const env = options.env ?? "production";
  if (diagnostics.length > 0) {
    writeDiagnostics(streams.stderr, diagnostics);
    return 1;
  }
  return runCompile([
    "--env", env,
    "--sources", join(repo, "deployment-sources.yml"),
    "--lock", join(repo, "deployment.lock.yml"),
    "--node-contract", join(repo, "inventory/node-contract.lock.yml"),
    "--reachability", join(repo, "catalog/reachability.yml"),
    "--out", join(repo, "cluster/flux"),
    ...(options.check ? ["--check"] : []),
  ], streams, parseOptions);
}

export function runImportFleetV1(args, streams, parseOptions) {
  const { options, diagnostics } = parseOptions(args);
  if (diagnostics.length > 0 || !options.fleet || !options.fluxTree || !options.out) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : usageDiagnostic("import-fleet-v1 --fleet <fleet.yaml> --flux-tree <dir> --out <dir>"));
    return 1;
  }
  const fleet = readDocument(options.fleet);
  const imported = {
    apiVersion: "deployment.jorisjonkers.dev/v2",
    kind: "Deployment",
    metadata: {
      name: basename(options.out).replace(/[^a-z0-9._-]/g, "-") || "imported-fleet",
      labels: {
        "deployment.jorisjonkers.dev/imported-from": "fleet-v1",
      },
    },
    spec: {
      services: importedServices(fleet, options.fluxTree),
    },
  };
  mkdirSync(options.out, { recursive: true });
  const deploymentPath = join(options.out, "deployment.yml");
  writeFileSync(deploymentPath, YAML.stringify(imported, { lineWidth: 0 }));
  streams.stdout.write(`${JSON.stringify({
    out: deploymentPath,
    services: Object.keys(imported.spec.services).length,
  }, null, 2)}\n`);
  return 0;
}

export function runParity(args, streams, parseOptions) {
  const { options, diagnostics } = parseOptions(args);
  if (diagnostics.length > 0 || !options.current || !options.rendered || options.allowFluxSourceDiff === undefined) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : usageDiagnostic("parity --current <old-tree> --rendered <new-tree> --allow-flux-source-diff true|false"));
    return 1;
  }
  const allowFluxSourceDiff = options.allowFluxSourceDiff === true || options.allowFluxSourceDiff === "true";
  const current = normalizedObjectMap(options.current, { allowFluxSourceDiff });
  const rendered = normalizedObjectMap(options.rendered, { allowFluxSourceDiff });
  const missing = [...current.keys()].filter((key) => !rendered.has(key)).sort();
  const extra = [...rendered.keys()].filter((key) => !current.has(key)).sort();
  const changed = [...current.keys()].filter((key) => rendered.has(key) && current.get(key) !== rendered.get(key)).sort();
  const ok = missing.length === 0 && extra.length === 0 && changed.length === 0;
  streams.stdout.write(`${JSON.stringify({ ok, missing, extra, changed }, null, 2)}\n`);
  return ok ? 0 : 1;
}

function runLockImages(args, streams, parseOptions) {
  const { options, diagnostics } = parseOptions(args);
  if (diagnostics.length > 0 || !options.lock) {
    writeDiagnostics(streams.stderr, diagnostics.length > 0 ? diagnostics : usageDiagnostic("lock images --lock deployment.lock.yml --format image-tags|json"));
    return 1;
  }
  const validation = validateNamedInputs([["deployment-lock-v1", options.lock]]);
  if (!validation.valid) {
    writeValidationResult(streams.stdout, validation);
    return 1;
  }
  const lock = readDocument(options.lock);
  const tags = imageTags(lock);
  if (options.format === "image-tags") {
    streams.stdout.write(`${tags.join("\n")}${tags.length > 0 ? "\n" : ""}`);
  } else {
    streams.stdout.write(`${JSON.stringify({ images: tags }, null, 2)}\n`);
  }
  return 0;
}

function resolveSourcesReport(sources, lock) {
  const sourceFirstParty = Object.keys(sources.spec?.firstParty ?? {});
  const lockedFirstParty = new Set(Object.keys(lock.inputs?.firstParty ?? {}));
  const sourceCollections = Object.keys(sources.spec?.collections ?? {});
  const lockedCollections = new Set(Object.keys(lock.inputs?.collections ?? {}));
  return {
    firstParty: sourceFirstParty,
    collections: sourceCollections,
    unlocked: [
      ...sourceFirstParty.filter((name) => !lockedFirstParty.has(name)).map((name) => `firstParty.${name}`),
      ...sourceCollections.filter((name) => !lockedCollections.has(name)).map((name) => `collections.${name}`),
    ],
  };
}

function compileReport(options) {
  const sources = readDocument(options.sources);
  const lock = readDocument(options.lock);
  const nodeContract = readDocument(options.nodeContract);
  const reachability = readDocument(options.reachability);
  return {
    env: options.env,
    sourcesDigest: fileDigest(options.sources),
    lockDigest: fileDigest(options.lock),
    nodeContractDigest: fileDigest(options.nodeContract),
    reachabilityDigest: fileDigest(options.reachability),
    firstParty: Object.keys(sources.spec?.firstParty ?? {}),
    collections: Object.keys(sources.spec?.collections ?? {}),
    lockedImages: imageTags(lock),
    nodes: Object.keys(nodeContract.nodes ?? {}),
    channels: Object.keys(reachability.channels ?? {}),
    rendererStatus: "scaffold",
    rendererRemaining: [
      "Kubernetes workload rendering",
      "Flux root tree rendering",
      "Traefik parity and v2 route rendering",
      "Gatus, VSO, NetworkPolicy, and Longhorn renderers",
    ],
  };
}

function compileFiles(report) {
  return [
    {
      path: "deploy-v2-compile-report.json",
      content: `${JSON.stringify(report, null, 2)}\n`,
    },
    {
      path: "kustomization.yaml",
      content: YAML.stringify({
        apiVersion: "kustomize.config.k8s.io/v1beta1",
        kind: "Kustomization",
        metadata: {
          annotations: {
            "deployment.jorisjonkers.dev/render-status": "scaffold",
          },
        },
        resources: [],
      }, { lineWidth: 0 }),
    },
  ];
}

function validateNamedInputs(inputs) {
  const results = inputs.map(([kind, path]) => {
    const validation = validateArtifact(kind, readDocument(path));
    return {
      file: path,
      kind,
      valid: validation.valid,
      diagnostics: validation.diagnostics,
    };
  });
  return {
    valid: results.every((result) => result.valid),
    diagnostics: results.flatMap((result) => result.diagnostics.map((diagnostic) => ({
      ...diagnostic,
      file: result.file,
      kind: result.kind,
    }))),
    results,
  };
}

function writeManagedFiles(files, root, options) {
  const results = files.map((file) => {
    const path = join(root, file.path);
    const content = `${generatedHeader}\n${file.content.trimEnd()}\n`;
    const current = existsSync(path) ? readFileSync(path, "utf8") : undefined;
    const action = current === content ? "unchanged" : current === undefined ? "create" : "update";
    return {
      path: file.path,
      action,
      currentHash: current === undefined ? undefined : sha256(current),
      nextHash: sha256(content),
      content,
    };
  });
  const ok = !options.check || results.every((result) => result.action === "unchanged");
  if (!options.check) {
    for (const result of results) {
      const path = join(root, result.path);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, result.content);
    }
  }
  return {
    ok,
    results: results.map(({ content: _content, ...result }) => result),
    diagnostics: ok ? [] : [{
      code: "E_RENDER_DIFF",
      message: "generated deploy-v2 files differ from disk",
      path: "/",
    }],
  };
}

function importedServices(fleet, fluxTree) {
  const names = new Set();
  collectNames(fleet?.fleet?.exposure?.services ?? {}, names);
  for (const path of listFiles(fluxTree)) {
    if (!/\.(ya?ml|json)$/.test(path)) continue;
    try {
      const docs = YAML.parseAllDocuments(readFileSync(path, "utf8")).map((doc) => doc.toJSON()).filter(Boolean);
      for (const doc of docs) {
        if (doc?.metadata?.name) names.add(doc.metadata.name);
      }
    } catch {
      // Import remains best-effort in the scaffold.
    }
  }
  if (names.size === 0) names.add("imported-service");
  return Object.fromEntries([...names].sort().map((name) => [slug(name), {
    image: "ghcr.io/jorisjonkers-dev/import-placeholder:latest",
    routes: [],
    observability: {
      gatus: [],
    },
  }]));
}

function normalizedObjectMap(root, options) {
  const objects = new Map();
  for (const path of listFiles(root).filter((item) => /\.(json|ya?ml)$/.test(item))) {
    const docs = YAML.parseAllDocuments(readFileSync(path, "utf8")).map((doc) => doc.toJSON()).filter(Boolean);
    for (const doc of docs) {
      const normalized = normalizeKubernetesObject(doc, options);
      const key = [
        normalized.apiVersion ?? "",
        normalized.kind ?? "",
        normalized.metadata?.namespace ?? "default",
        normalized.metadata?.name ?? relative(root, path),
      ].join("/");
      objects.set(key, JSON.stringify(sortKeys(normalized)));
    }
  }
  return objects;
}

function normalizeKubernetesObject(value, options) {
  const copy = structuredClone(value);
  delete copy.metadata?.creationTimestamp;
  delete copy.metadata?.resourceVersion;
  delete copy.metadata?.uid;
  if (options.allowFluxSourceDiff && copy.kind === "GitRepository") {
    delete copy.spec?.url;
    delete copy.spec?.ref?.branch;
  }
  if (options.allowFluxSourceDiff && copy.kind === "Kustomization" && copy.metadata?.name === "production") {
    delete copy.spec?.path;
  }
  return copy;
}

function imageTags(lock) {
  const firstParty = Object.values(lock.inputs?.firstParty ?? {}).flatMap((entry) => entry.images ?? []);
  const direct = Object.values(lock.inputs?.images ?? {});
  return [...new Set([...firstParty, ...direct])].sort();
}

function readDocument(path) {
  return loadConfig(path);
}

function stringifyDocument(path, value) {
  return path.endsWith(".json") ? `${JSON.stringify(value, null, 2)}\n` : YAML.stringify(value, { lineWidth: 0 });
}

function fileDigest(path) {
  return sha256(readFileSync(path));
}

function sha256(value) {
  return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

function listFiles(root) {
  if (!existsSync(root)) return [];
  const stats = statSync(root);
  if (!stats.isDirectory()) return [root];
  return readdirSync(root).flatMap((entry) => {
    const path = join(root, entry);
    return statSync(path).isDirectory() ? listFiles(path) : [path];
  }).sort();
}

function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(Object.entries(value).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => [key, sortKeys(item)]));
}

function collectNames(value, target) {
  for (const key of Object.keys(value)) target.add(key);
}

function slug(value) {
  return String(value).toLowerCase().replace(/[^a-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || "imported-service";
}

function optionName(value) {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function writeValidationResult(stream, validation) {
  stream.write(`${JSON.stringify(validation, null, 2)}\n`);
}

function writeDiagnostics(stream, diagnostics) {
  writeValidationResult(stream, {
    valid: false,
    diagnostics,
  });
}

function usageDiagnostic(command) {
  return [
    {
      code: "E_USAGE",
      message: `usage: deploy-config-schema ${command}`,
      path: "/",
    },
  ];
}
