import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { ignoreOverride, zodToJsonSchema } from "zod-to-json-schema";
import {
  deployConfigJsonSchema,
  deployConfigSchema,
  collectionJsonSchema,
  collectionSchema,
  deploymentEnvJsonSchema,
  deploymentEnvSchema,
  deploymentLockJsonSchema,
  deploymentLockSchema,
  deploymentSourcesJsonSchema,
  deploymentSourcesSchema,
  deploymentJsonSchema,
  deploymentSchema,
  fleetInventoryJsonSchema,
  fleetInventorySchema,
  nodeContractJsonSchema,
  nodeContractSchema,
  platformJsonSchema,
  platformSchema,
  reachabilityJsonSchema,
  reachabilitySchema,
  serviceIntentJsonSchema,
  serviceIntentSchema,
  stateMovePlanJsonSchema,
  stateMovePlanSchema,
  vaultDynamicSecretsJsonSchema,
  vaultDynamicSecretsSchema,
} from "../src/schemas/index.js";

const entries = [
  ["schemas/platform.schema.json", "platformJsonSchema", platformSchema, platformJsonSchema],
  ["schemas/deploy-config.schema.json", "deployConfigJsonSchema", deployConfigSchema, deployConfigJsonSchema],
  ["schemas/round3/service-intent.schema.json", "serviceIntentJsonSchema", serviceIntentSchema, serviceIntentJsonSchema],
  ["schemas/round3/fleet-inventory.schema.json", "fleetInventoryJsonSchema", fleetInventorySchema, fleetInventoryJsonSchema],
  ["schemas/round3/vault-dynamic-secrets.schema.json", "vaultDynamicSecretsJsonSchema", vaultDynamicSecretsSchema, vaultDynamicSecretsJsonSchema],
  ["schemas/deployment.schema.json", "deploymentJsonSchema", deploymentSchema, deploymentJsonSchema],
  ["schemas/deployment-env.schema.json", "deploymentEnvJsonSchema", deploymentEnvSchema, deploymentEnvJsonSchema],
  ["schemas/deployment-sources.schema.json", "deploymentSourcesJsonSchema", deploymentSourcesSchema, deploymentSourcesJsonSchema],
  ["schemas/deployment-lock.schema.json", "deploymentLockJsonSchema", deploymentLockSchema, deploymentLockJsonSchema],
  ["schemas/node-contract.schema.json", "nodeContractJsonSchema", nodeContractSchema, nodeContractJsonSchema],
  ["schemas/collection.schema.json", "collectionJsonSchema", collectionSchema, collectionJsonSchema],
  ["schemas/reachability.schema.json", "reachabilityJsonSchema", reachabilitySchema, reachabilityJsonSchema],
  ["schemas/state-move-plan.schema.json", "stateMovePlanJsonSchema", stateMovePlanSchema, stateMovePlanJsonSchema],
] as const;

const check = process.argv.includes("--check");
let stale = false;

for (const [relativePath, _exportName, zodSchema, jsonSchema] of entries) {
  const generated = structuredClone(jsonSchema);
  zodToJsonSchema(zodSchema, {
    target: "jsonSchema2019-09",
    $refStrategy: "root",
    override: (_def, refs) => (refs.currentPath.join("/") === "#" ? generated : ignoreOverride),
  });
  const text = `${JSON.stringify(jsonSchema, null, 2)}\n`;
  const path = resolve(relativePath);

  if (check) {
    const current = readFileSync(path, "utf8");
    if (current !== text) {
      console.error(`${relativePath} is stale; run npm run build:schemas`);
      stale = true;
    }
    continue;
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

const bridgeText = generatedJsonBridgeText();
if (check) {
  const bridgePath = resolve("src/schemas/generated-json.js");
  const current = readFileSync(bridgePath, "utf8");
  if (current !== bridgeText) {
    console.error("src/schemas/generated-json.js is stale; run npm run build:schemas");
    stale = true;
  }
} else {
  writeGeneratedJsonBridge();
}

if (stale) {
  process.exitCode = 1;
}

function writeGeneratedJsonBridge() {
  writeFileSync(resolve("src/schemas/generated-json.js"), generatedJsonBridgeText());
}

function generatedJsonBridgeText() {
  const chunks = ["// Generated by scripts/generate-schemas.ts. Do not edit by hand.\n"];
  for (const [_relativePath, exportName, _zodSchema, jsonSchema] of entries) {
    chunks.push(`export const ${exportName} = ${JSON.stringify(jsonSchema, null, 2)};\n`);
  }
  return chunks.join("\n");
}
