import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { ignoreOverride, zodToJsonSchema } from "zod-to-json-schema";
import {
  deployConfigJsonSchema,
  deployConfigSchema,
  collectionV1JsonSchema,
  collectionV1Schema,
  deploymentEnvV1JsonSchema,
  deploymentEnvV1Schema,
  deploymentLockV1JsonSchema,
  deploymentLockV1Schema,
  deploymentSourcesV1JsonSchema,
  deploymentSourcesV1Schema,
  deploymentV2JsonSchema,
  deploymentV2Schema,
  fleetInventoryJsonSchema,
  fleetInventorySchema,
  nodeContractV1JsonSchema,
  nodeContractV1Schema,
  platformJsonSchema,
  platformSchema,
  reachabilityV1JsonSchema,
  reachabilityV1Schema,
  serviceIntentJsonSchema,
  serviceIntentSchema,
  stateMovePlanV1JsonSchema,
  stateMovePlanV1Schema,
  vaultDynamicSecretsJsonSchema,
  vaultDynamicSecretsSchema,
} from "../src/schemas/index.js";

const entries = [
  ["schemas/platform.schema.json", "platformJsonSchema", platformSchema, platformJsonSchema],
  ["schemas/deploy-config.schema.json", "deployConfigJsonSchema", deployConfigSchema, deployConfigJsonSchema],
  ["schemas/round3/service-intent.schema.json", "serviceIntentJsonSchema", serviceIntentSchema, serviceIntentJsonSchema],
  ["schemas/round3/fleet-inventory.schema.json", "fleetInventoryJsonSchema", fleetInventorySchema, fleetInventoryJsonSchema],
  ["schemas/round3/vault-dynamic-secrets.schema.json", "vaultDynamicSecretsJsonSchema", vaultDynamicSecretsSchema, vaultDynamicSecretsJsonSchema],
  ["schemas/deployment/v2.schema.json", "deploymentV2JsonSchema", deploymentV2Schema, deploymentV2JsonSchema],
  ["schemas/deployment-env/v1.schema.json", "deploymentEnvV1JsonSchema", deploymentEnvV1Schema, deploymentEnvV1JsonSchema],
  ["schemas/deployment-sources/v1.schema.json", "deploymentSourcesV1JsonSchema", deploymentSourcesV1Schema, deploymentSourcesV1JsonSchema],
  ["schemas/deployment-lock/v1.schema.json", "deploymentLockV1JsonSchema", deploymentLockV1Schema, deploymentLockV1JsonSchema],
  ["schemas/node-contract/v1.schema.json", "nodeContractV1JsonSchema", nodeContractV1Schema, nodeContractV1JsonSchema],
  ["schemas/collection/v1.schema.json", "collectionV1JsonSchema", collectionV1Schema, collectionV1JsonSchema],
  ["schemas/reachability/v1.schema.json", "reachabilityV1JsonSchema", reachabilityV1Schema, reachabilityV1JsonSchema],
  ["schemas/state-move-plan/v1.schema.json", "stateMovePlanV1JsonSchema", stateMovePlanV1Schema, stateMovePlanV1JsonSchema],
] as const;

const check = process.argv.includes("--check");
let stale = false;

for (const [relativePath, _exportName, zodSchema, jsonSchema] of entries) {
  const generated = structuredClone(jsonSchema);
  zodToJsonSchema(zodSchema, {
    target: "jsonSchema2019-09",
    $refStrategy: "root",
    override: (_def, refs) => (refs.currentPath.join("/") === "#" ? generated : ignoreOverride),
  });
  const text = `${JSON.stringify(jsonSchema, null, 2)}\n`;
  const path = resolve(relativePath);

  if (check) {
    const current = readFileSync(path, "utf8");
    if (current !== text) {
      console.error(`${relativePath} is stale; run npm run build:schemas`);
      stale = true;
    }
    continue;
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

const bridgeText = generatedJsonBridgeText();
if (check) {
  const bridgePath = resolve("src/schemas/generated-json.js");
  const current = readFileSync(bridgePath, "utf8");
  if (current !== bridgeText) {
    console.error("src/schemas/generated-json.js is stale; run npm run build:schemas");
    stale = true;
  }
} else {
  writeGeneratedJsonBridge();
}

if (stale) {
  process.exitCode = 1;
}

function writeGeneratedJsonBridge() {
  writeFileSync(resolve("src/schemas/generated-json.js"), generatedJsonBridgeText());
}

function generatedJsonBridgeText() {
  const chunks = ["// Generated by scripts/generate-schemas.ts. Do not edit by hand.\n"];
  for (const [_relativePath, exportName, _zodSchema, jsonSchema] of entries) {
    chunks.push(`export const ${exportName} = ${JSON.stringify(jsonSchema, null, 2)};\n`);
  }
  return chunks.join("\n");
}
