import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { createHash, randomUUID } from "node:crypto";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { safeRelativePath } from "./paths.js";
import type { AdapterFile } from "../adapters/model.js";

export const generatedHeader = "# Generated by deploy-config-schema platform renderer. Edit platform.yaml instead.";

export type WriteGeneratedFilesOptions = {
  root?: string;
  force?: boolean;
  dryRun?: boolean;
  diff?: boolean;
};

export type WriteAction = "blocked" | "create" | "update" | "unchanged";

export type PreparedWrite = {
  path: string;
  absolutePath: string;
  adapter: string;
  action: WriteAction;
  currentHash?: string;
  nextHash: string;
  content: string;
};

export type WriteGeneratedFilesResult = {
  ok: boolean;
  results: PreparedWrite[];
  diagnostics: Array<{ code: string; message: string; path: string }>;
};

export function renderManagedContent(content: string): string {
  const body = content.endsWith("\n") ? content.trimEnd() : content;
  return `${generatedHeader}\n${body}\n`;
}

export function writeGeneratedFiles(files: AdapterFile[], options: WriteGeneratedFilesOptions = {}): WriteGeneratedFilesResult {
  const root = options.root ?? ".";
  const force = options.force === true;
  const dryRun = options.dryRun === true;
  const diff = options.diff === true;
  const results = files.map((file) => prepareWrite(root, file, { force }));
  const blocked = results.filter((result) => result.action === "blocked");
  if (blocked.length > 0) {
    return {
      ok: false,
      results,
      diagnostics: blocked.map((result) => ({
        code: "E_RENDER_OVERWRITE_REFUSED",
        message: `refusing to overwrite unmanaged file ${result.path}`,
        path: result.path
      }))
    };
  }

  if (!dryRun && !diff) {
    for (const result of results) {
      if (result.action === "unchanged") continue;
      mkdirSync(dirname(result.absolutePath), { recursive: true });
      const tempPath = join(tmpdir(), `deploy-config-schema-${randomUUID()}`);
      writeFileSync(tempPath, result.content);
      renameSync(tempPath, result.absolutePath);
    }
  }

  return {
    ok: diff ? results.every((result) => result.action === "unchanged") : true,
    results,
    diagnostics: diff && results.some((result) => result.action !== "unchanged")
      ? [{
          code: "E_RENDER_DIFF",
          message: "generated files differ from disk",
          path: "/"
        }]
      : []
  };
}

function prepareWrite(root: string, file: AdapterFile, options: { force: boolean }): PreparedWrite {
  const path = safeRelativePath(file.path);
  const absolutePath = join(root, path);
  const content = renderManagedContent(file.content);
  const exists = existsSync(absolutePath);
  const current = exists ? readFileSync(absolutePath, "utf8") : "";
  const managed = current.startsWith(generatedHeader);
  const changed = current !== content;

  if (exists && !managed && !options.force) {
    return {
      path,
      absolutePath,
      adapter: file.adapter,
      action: "blocked",
      currentHash: hash(current),
      nextHash: hash(content),
      content
    };
  }
  return {
    path,
    absolutePath,
    adapter: file.adapter,
    action: changed ? (exists ? "update" : "create") : "unchanged",
    currentHash: exists ? hash(current) : undefined,
    nextHash: hash(content),
    content
  };
}

function hash(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}
